source:
  type: simulation
  topic: /camera
  rate: 30
detector:
  enabled: true
  overlay_enabled: true
  low_h: 0
  low_s: 100
  low_v: 100
  high_h: 10
  high_s: 255
  high_v: 255
video_local: false
codec: h264
host: 127.0.0.1
port: 5600
mtu: 800
